program: src/policy_eval.py
name: policy_ground_truth
project: policy_eval
description: calculate ground truth value for policies
method: grid
parameters:
  env_id:
    values: ["MultiBandit"]
  seed:
    values: [10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
  policy:
    values: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000]
  num_episodes:
    values: [100000]
  sampler: 
    values: ["GroundTruth"]

